# GitHub Actions 工作流配置文件 - Android平台编译
# 该文件用于配置在Android环境下自动编译项目的CI/CD流程

name: Android  # 工作流名称

# 触发条件配置
on:
  push:
    branches: [main, develop, 'feature/**']
    paths:
      - 'framework/**'
      - 'plugin/**'
      - 'python/src/**'
      - 'test/**'
      - 'demo/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [main]
    paths:
      - 'framework/**'
      - 'plugin/**'
      - 'python/src/**'
      - 'test/**'
      - 'demo/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/android.yml'

# 环境变量定义
env:
  ANDROID_API_LEVEL: 21
  ANDROID_NDK_VERSION: r25c

# 工作任务定义
jobs:
  build:
    name: Android编译构建
    runs-on: ubuntu-latest
  
    steps:
      # 检出源代码
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      # 设置JDK环境
      - name: 设置JDK环境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # 设置Rust工具链
      - name: 设置Rust工具链
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          
      # 添加Android目标平台
      - name: 添加Android目标平台
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi
          
      # 安装Android开发工具
      - name: 安装Android开发工具
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build
            
      # 设置Android NDK
      - name: 设置Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          
      # 配置CMake构建环境
      - name: 配置构建
        run: |
          mkdir build
          cp cmake/config_minimal.cmake build/config.cmake
          cd build
          cmake -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release \
            ..
      
      # 执行编译
      - name: 编译
        run: |
          cd build
          ninja -j$(nproc)
          
      # 验证编译结果
      - name: 编译结果检查
        run: |
          cd build
          ls -la
          echo "Android arm64-v8a 架构 API21 编译完成"
          
      # 上传编译产物
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a-api21-release-libs
          path: build/lib/
          retention-days: 7
